### ISSUE TITLE
Unable to switch Eufy lightbulb on or off

### ISSUE THREAD

**Issue by ingorichter** [sebmos/homebridge-eufy#13]
I have a Eufy T1013 lightbulb and I can control it from the app and from https://github.com/sebmos/node-eufy-api
Unfortunately, I can't control it in homebridge. The lightbulb appears in the device list.
I'm using homebridge 1.2.5 and version 0.3.3 of the bridge

```
[1/28/2021, 8:29:18 PM] [eufy] Error getting color saturation on device: Leselampe  -  Error: Socket closed without sending response
    at Timeout.<anonymous> (/homebridge/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[1/28/2021, 8:29:18 PM] [eufy] Error getting temperature on device: Leselampe  -  Error: Socket closed without sending response
    at Timeout.<anonymous> (/homebridge/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[1/28/2021, 8:29:18 PM] [eufy] Error loading power state on device: Leselampe  -  Error: Socket closed without sending response
    at Timeout.<anonymous> (/homebridge/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[1/28/2021, 8:29:18 PM] [eufy] Error getting brightness on device: Leselampe  -  Error: Socket closed without sending response
    at Timeout.<anonymous> (/homebridge/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[1/28/2021, 8:29:18 PM] [eufy] Error getting color hue on device: Leselampe  -  Error: Socket closed without sending response
    at Timeout.<anonymous> (/homebridge/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by sebmos** [comment]
Can you double-check what the exact version of node-eufy-api is inside the homebridge package, in `/homebridge/node_modules/homebridge-eufy/node_modules/node-eufy-api/package.json`?

**Comment by ingorichter** [comment]
it's 0.3.3 according to package.json

**Comment by scottjl** [comment]
same problem here. can't use this with my eufy bulbs at all, any of them.

**Comment by sebmos** [comment]
As part of node-eufy-api v0.3.4 / homebridge-eufy v0.3.5, I added some additional logging that would explicitly log out if the device is about to fail due to a known issue with Eufy devices. I assume you're on the latest version @scottjl, but can you double-check that you are, and post your logs here?

**Comment by scottjl** [comment]
@sebmos  actually. i decided i had enough of dealing with homekit unsupported eufy equipment, rage quit, and took them all out. gone. done with eufy. thank you for your efforts and wish you the best.

**Comment by sebmos** [comment]
@scottjl Can't blame you - I did the same!
