### ISSUE TITLE
Eufy Smart Switch Error

### ISSUE THREAD

**Issue by jbibi-home** [sebmos/homebridge-eufy#17]
I have been using this plugin for months with no issue.
Within the last couple of days I realized that this Homebridge plugin was not finding my smart switches.
Here is the log with the issue
```
11/9/2021, 11:12:03 AMEufy Bridge starting
11/9/2021, 11:12:09 AMEufy BridgeLoaded plugin 'homebridge-eufy'
11/9/2021, 11:12:09 AMEufy BridgeLoading 1 platforms...
11/9/2021, 11:12:09 AMEufy BridgeeufyhomeEufy initializing
11/9/2021, 11:12:09 AMEufy BridgeBridge is running on port 51846.
11/9/2021, 11:12:10 AMEufy BridgeeufyhomeAdd Accessory: Den Lights - 5HE38J93H27BH33
11/9/2021, 11:12:10 AMEufy BridgeeufyhomeAdd Accessory: Bedroom Lights - 2FE78004CC1C4607
11/9/2021, 11:12:12 AMEufy BridgeeufyhomeError connecting to accessory: Error: Socket closed without sending response
    at Timeout.<anonymous> (/var/lib/hoobs/eufybridge/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
11/9/2021, 11:12:12 AMEufy BridgeeufyhomeRemoving accessory: Den Lights
11/9/2021, 11:12:12 AMEufy BridgeeufyhomeError connecting to accessory: Error: Socket closed without sending response
    at Timeout.<anonymous> (/var/lib/hoobs/eufybridge/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
11/9/2021, 11:12:12 AMEufy BridgeeufyhomeRemoving accessory: Bedroom Lights
11/9/2021, 11:12:12 AMEufy BridgeeufyhomeError loading power state on device: Den Lights  -  Error: Socket closed without sending response
    at Timeout.<anonymous> (/var/lib/hoobs/eufybridge/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
11/9/2021, 11:12:12 AMEufy BridgeeufyhomeError loading power state on device: Bedroom Lights  -  Error: Socket closed without sending response
    at Timeout.<anonymous> (/var/lib/hoobs/eufybridge/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

**Comment by jbibi-home** [comment]
I got this error in the logs as well:
`BridgeWARNING: There is a firmware bug your device that means that it will disconnect! There is no known workaround for this.`

**Comment by sebmos** [comment]
The warning gives the problem away - there's a bug in the Eufy plugs that means that some devices don't work (or stop working after a while). There's not much I can do about this, unfortunately - I'm not aware of anybody else solving that problem, either.

**Comment by ibmaster** [comment]
Confirming doing a device hard reset and re-add of device to your eufy account still a viable (though painful) workaround to recover the Homebridge operation of eufy's wall switch.
