### ISSUE TITLE
Accessories No Longer Appear

### ISSUE THREAD

**Issue by cargueta001** [sebmos/homebridge-eufy#4]
@sebmos Yesterday, after rebooting my Raspberry Pi, the plugin attempted to start and received several errors. Prior, everything worked as normal and was able to setup successfully. No changes were made other than a reboot. Any help would be greatly appreciated.
![5BD2B7BD-B5CD-4E46-BEBF-D715BCB0E83F](https://user-images.githubusercontent.com/48275759/56471954-68f8d080-640d-11e9-8e38-9d60dc8c867a.png)

**Comment by nathsea** [comment]
Hi I appear to be having the same issue. Updated my version of homebridge on hoobs and now I don’t have two of my lights , one of the three is still there but defaulted back to a different room.

**Comment by cargueta001** [comment]
@nathsea I was able to resolve this on my own as the developer has not responded.

What I did to resolve this required me to go the Eufy app and remove each plug and reinstall accordingly. Once I did this, I rebooted Homebridge and then the accessories appeared as it should have. I kept the same naming conventions to avoid duplicates and multiple instances. Hopefully this helps with your issue as well.

**Comment by sebmos** [comment]
@cargueta001 - Thanks for the workaround - I wasn't aware of that!

This is a known issue/a bug (also reported here: https://github.com/sebmos/node-eufy-api/issues/2) with Eufy's local API, and I haven't managed to "decode" their remote API works (which the app is using as a fallback automatically.)

I'll re-open the story in case somebody else runs into this problem, since the bug is not properly resolved at this point.

**Comment by nathsea** [comment]
@cargueta001 thanks that is great I will give it a go 👍

**Comment by martinsirbe** [comment]
I'm seeing the same error:
```[5/6/2019, 8:43:23 PM] [eufy] Error connecting to accessory: Error: Socket closed without sending response
    at Timeout.<anonymous> (/opt/node/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)```

**Comment by martinsirbe** [comment]
I'm seeing the same error:
```[5/6/2019, 8:43:23 PM] [eufy] Error connecting to accessory: Error: Socket closed without sending response
    at Timeout.<anonymous> (/opt/node/lib/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```
Update:
Reseting a single plug worked (all other plugs became available), however didn't work for bulbs.

**Comment by nathsea** [comment]
Hi still having issues , deleting one plug of the three , gave me two back , but I cannot get the last one to add back in ... I have deleted it and changed the name and when it finds it in the log , it deletes it straight away 🤔

**Comment by nathsea** [comment]
Just rebooted homebridge and all of the sockets have disappeared again ...

**Comment by ghost** [comment]
Error connecting to accessory: Error: Socket closed without sending response

whats the problem and how to fix it   i have a eufy bulb so pleaseeeee  answer

**Comment by spartaaa-git** [comment]
I removed devices, and added them again in the eufy portal app, but ran into trouble again after adding them back. I am specifically having trouble with the eufy smart plugs.
