### ISSUE TITLE
Socket Closed without sending response

### ISSUE THREAD

**Issue by decavent** [sebmos/homebridge-eufy#6]
Hi, I’m getting an error when booting up Homebridge. Both are Eufy white/color bulbs. As Homebridge starts, I see the plugin “Add Accessory” and identify each bulb. However, it then generates and error “connecting to accessory: Error: Socket closed without sending response.” It then removes the accessory (bulb). Any thoughts? Tried reinstalling the plugin.

**Comment by digitalec** [comment]
I believe it was a change to the Eufy API. See issues 2, 4, 5 & 6 at https://github.com/sebmos/node-eufy-api

I ended up dumping my bulbs and went with a bunch of Tuya stuff

**Comment by dancocos** [comment]
Is this module dead for now? If so I think noting this on the readme page should be mentioned.

**Comment by sebmos** [comment]
@dancocos I wouldn't call it dead, as it still works for _some_ lights. I still hold out hope that Eufy will fix the bug in their firmware. But it's true that this API doesn't support their server-side API, which Eufy uses for remote control (and as a fallback for the same bug, which they're also affected by.)

**Comment by jgadzhiev** [comment]
> @dancocos I wouldn't call it dead, as it still works for _some_ lights. I still hold out hope that Eufy will fix the bug in their firmware. But it's true that this API doesn't support their server-side API, which Eufy uses for remote control (and as a fallback for the same bug, which they're also affected by.)

Dear @sebmos 
May I ask if there is indication of Eufy has made a mentioned fix or not? 
Thank you.

**Comment by sebmos** [comment]
@jgadzhiev - My response is a bit slow, as I had to start using the Eufy plugs again. It appears the bug isn't fixed, sadly. My bulbs worked for a bit, and then they stopped.

**Comment by viseshrp** [comment]
Still see the same problem.

```
[12/2/2022, 5:14:25 PM] [eufy] Error loading power state on device: Google home  -  Error: Socket closed without sending response
    at Timeout.<anonymous> (/homebridge/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
[12/2/2022, 5:14:25 PM] [eufy] Error connecting to accessory: Error: Socket closed without sending response
    at Timeout.<anonymous> (/homebridge/node_modules/homebridge-eufy/node_modules/node-eufy-api/lib/tcp-socket.js:153:48)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
[12/2/2022, 5:14:25 PM] [eufy] Removing accessory: Google home
```

@sebmos any solutions or alternatives?
